CREATE TABLE HOTEL.CLIENT (
    CLIENTID INT,
    FIRSTNAME VARCHAR2(50),
    LASTNAME VARCHAR2(50),
    STUDENTDISCOUNT FLOAT,
    MEMBERSHIPDISCOUNT FLOAT,
    CREDITDISCOUNT FLOAT,
    POINTS INT,
    ISSTUDENT BOOL,
    MEMBERSHIPTYPE VARCHAR2(10),
    PRIMARY KEY(CLIENTID)
);

CREATE TABLE HOTEL.BOOKING (
    CLIENTID INT,
    HOTELID INT,
    ROOMID INT,
    STARTDATE DATE,
    ENDDATE DATE,
    PRIMARY KEY(CLIENTID, HOTELID, ROOMID, STARTDATE)
);

CREATE TABLE HOTEL.HOTEL (
    HOTELID INT,
    NAME VARCHAR2(75),
    PRIMARY KEY(HOTELID)
);

CREATE TABLE HOTEL.ROOM (
    ROOMID INT,
    HOTELID INT,
    AMENITIESTOTAL MONEY,
    ROOMRATE MONEY,
    PRIMARY KEY(ROOMID, HOTELID)
);

CREATE TABLE HOTEL.AMENITY (
    AMENITYID INT,
    HOTELID INT,
    AMENITYNAME VARCHAR2(50);

RATINGID INT,

PRIMARY KEY(AMENITYID, HOTELID)

);

CREATE TABLE HOTEL.RATING (
    RATINGID INT,
    RATING INT,
    COMMENTS VARCHAR2(250) AMENITYID INT,
    PRIMARY KEY(RATINGID)
);

CREATE TABLE HOTEL.EMPLOYEE (
    EMPLOYEEID INT,
    HOTELID INT,
    FIRSTNAME VARCHAR2(50) LASTNAME VARCHAR2(50) DUTY VARCHAR2(50) WAGE MONEY PRIMARY KEY(EMPLOYEEID, HOTELID)
);

CREATE TABLE HOTEL.SHIFT (
    EMPLOYEEID INT,
    DATESTART DATETIME DATEEND DATETIME PRIMARY KEY(EMPLOYEEID, DATESTART)
);