/*
 * Amenity.java -- Object containing all the data necessary for a single Amenity record for Prog4.java
 * 		   		-- This represents the amenities that a hotel offers.
 *             	-- Also contains toString() and GetFields() methods.
 *
 * Author: Mauricio Brooks, Mason Mariani, Arnav Popat
 *
 * First Version: 2023-05-02.
 */

package prog4;

import java.lang.reflect.Field;
import java.util.UUID;

/*+----------------------------------------------------------------------
 ||
 ||  Class Amenity 
 ||
 ||         Author:  Mauricio Brooks, Mason Mariani, Arnav Popat
 ||        Purpose:  Object containing all the data necessary for a single 
 ||						Amenity in a hotel for Prog4.java
 ||                   
 ||
 ||  Inherits From:  None.
 ||
 ||     Interfaces:  None.
 ||
 |+-----------------------------------------------------------------------
 ||	
 ||      Fields:  
 ||                 public String amenityId -- unique id of amenity,
 || 					 generated by UUID.randomUUID().toString()
 ||                 public String hotelId -- unique id of hotel offering
 ||						 this amenity
 ||                 public String amenityName -- name of the amenity 
 ||						i.e. "pool"
 ||                 
 ||
 |+-----------------------------------------------------------------------
 ||
 ||   Constructors:  Amenity(String hotelId, String amenityName)
 ||
 ||  Inst. Methods:  public String toString() -- returns field vals as a comma-separated string
 ||                  String getFields() -- returns field names matching DB columns
 ||                  
 ++-----------------------------------------------------------------------*/
public class Amenity {

	public String amenityId;
	public String hotelId;
	public String amenityName;
	public int ratingId;

	public Amenity(String hotelId, String amenityName) {
		this.amenityId = UUID.randomUUID().toString();
		this.hotelId = hotelId;
		this.amenityName = amenityName;
	}

	@Override
	public String toString() {
		return amenityId + ", " + hotelId + ", " + amenityName + ", " + ratingId;
	}

	public String GetFields() {

		StringBuilder sb = new StringBuilder();
		Field[] fields = this.getClass().getDeclaredFields();
		for (Field field : fields) {
			sb.append(field.getName()).append(", ");
		}
		sb.delete(sb.length() - 2, sb.length()); // remove the last ", "
		return sb.toString();
	}

}
