/*
 * Booking.java -- Object containing all the data necessary for a single Booking record for Prog4.java
 * 		   		-- This represents the data required for Booking table.
 *             	-- Also contains toString() and GetFields() methods.
 *
 * Author: Mauricio Brooks, Mason Mariani, Arnav Popat
 *
 * First Version: 2023-05-02.
 */

package prog4;

import java.lang.reflect.Field;
import java.sql.Date;

/*+----------------------------------------------------------------------
 ||
 ||  Class Booking 
 ||
 ||         Author:  Mauricio Brooks, Mason Mariani, Arnav Popat
 ||        Purpose:  Object containing all the data necessary for a single 
 ||						Booking in a hotel for Prog4.java
 ||                   
 ||
 ||  Inherits From:  None.
 ||
 ||     Interfaces:  None.
 ||
 |+-----------------------------------------------------------------------
 ||		
 ||      Fields:  
 ||                 public String clientId -- unique id of booking,
 || 					 generated by UUID.randomUUID().toString()
 ||                 public String hotelId -- unique id of hotel for
 ||						 this booking
 ||                 public String roomId; -- id of the room for  
 ||						this booking
 ||                 public Date startDate -- start date of 
 ||						this booking
 ||                 public Date endDate -- end date of
 ||						this booking
 ||                 
 ||
 |+-----------------------------------------------------------------------
 ||
 ||   Constructors:  public Booking (String clientId, String hotelId, 
 ||						String roomId, Date startDate, Date endDate)
 ||
 ||  Inst. Methods:  public String toString() -- returns fields vals as a comma-separated string
 ||                  String getFields() -- returns field names matching DB columns
 ||                  
 ++-----------------------------------------------------------------------*/
public class Booking {

	public String clientId;
	public String hotelId;
	public String roomId;
	public Date startDate;
	public Date endDate;

	public Booking(String clientId, String hotelId, String roomId, Date startDate, Date endDate) {
		this.clientId = clientId;
		this.hotelId = hotelId;
		this.roomId = roomId;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public String toString() {
		return clientId + ", " + hotelId + ", " + roomId + ", " + startDate + ", " + endDate;
	}

	public String GetFields() {

		StringBuilder sb = new StringBuilder();
		Field[] fields = this.getClass().getDeclaredFields();
		for (Field field : fields) {
			sb.append(field.getName()).append(", ");
		}
		sb.delete(sb.length() - 2, sb.length()); // remove the last ", "
		return sb.toString();
	}

}
