/*
 * Client.java -- Object containing all the data necessary for a single Client record for Prog4.java
 * 		   		-- This represents the data required for Client table.
 *             	-- Also contains toString() and GetFields() methods.
 *
 * Author: Mauricio Brooks, Mason Mariani, Arnav Popat
 *
 * First Version: 2023-05-02.
 */

package prog4;

import java.lang.reflect.Field;
import java.util.UUID;

/*+----------------------------------------------------------------------
 ||
 ||  Class Client 
 ||
 ||         Author:  Mauricio Brooks, Mason Mariani, Arnav Popat
 ||        Purpose:  Object containing all the data necessary for a single 
 ||						Client in the hotel company DB for Prog4.java
 ||                   
 ||
 ||  Inherits From:  None.
 ||
 ||     Interfaces:  None.
 ||
 |+-----------------------------------------------------------------------
 ||			
 ||      Fields:  
 ||                 public String clientId -- unique id of client,
 || 					 generated by UUID.randomUUID().toString()
 ||                 public String firstName -- client first name
 ||					public String lastName -- client last name
 ||                 public bool membershipDiscount -- true or false
 ||                 public bool creditDiscount -- true or false
 ||					public int points -- number of rewards points
 ||					public bool isStudent -- true or false
 ||                 public String membershipType -- none, bronze,
 ||						silver, gold
 ||                 
 ||
 |+-----------------------------------------------------------------------
 ||
 ||   Constructors:  public Client(String firstName, String lastName)
 ||
 ||  Inst. Methods:  public String toString() -- returns field vals as a comma-separated string
 ||                  String getFields() -- returns field names matching DB columns
 ||                  
 ++-----------------------------------------------------------------------*/
public class Client {

	public String clientId;
	public String firstName;
	public String lastName;
	public float studentDiscount;
	public float membershipDiscount;
	public float creditDiscount;
	public int points;
	public boolean isStudent;
	public String membershipType; // none, bronze, silver, gold

	public Client(String firstName, String lastName) {
		this.firstName = firstName;
		this.lastName = lastName;

		// Set default values for the other fields
		this.clientId = UUID.randomUUID().toString();
		this.isStudent = false;
		this.membershipType = "none";
		this.studentDiscount = 0;
		this.membershipDiscount = 0;
		this.creditDiscount = 0;
		this.points = 0;
	}

	public String GetFields() {

		StringBuilder sb = new StringBuilder();
		Field[] fields = this.getClass().getDeclaredFields();
		for (Field field : fields) {
			sb.append(field.getName()).append(", ");
		}
		sb.delete(sb.length() - 2, sb.length()); // remove the last ", "
		return sb.toString();
	}

	@Override
	public String toString() {
		return clientId + "," + firstName + "," + lastName + "," + studentDiscount + "," + membershipDiscount + "," +
				creditDiscount + "," + points + "," + isStudent + "," + membershipType;
	}

}
