/*
 * Hotel.java -- Object containing all the data necessary for a single Hotel record for Prog4.java
 * 		   		-- This represents the data required for Hotel table.
 *             	-- Also contains toString() and GetFields() methods.
 *
 * Author: Mauricio Brooks, Mason Mariani, Arnav Popat
 *
 * First Version: 2023-05-02.
 */

package prog4;

import java.lang.reflect.Field;
import java.util.UUID;

/*+----------------------------------------------------------------------
 ||
 ||  Class Hotel 
 ||
 ||         Author:  Mauricio Brooks, Mason Mariani, Arnav Popat
 ||        Purpose:  Object containing all the data necessary for a single 
 ||						Hotel in the hotel company DB for Prog4.java
 ||                   
 ||
 ||  Inherits From:  None.
 ||
 ||     Interfaces:  None.
 ||
 |+-----------------------------------------------------------------------
 ||      Fields:  
 ||                 public String hotelId -- unique id of hotel,
 || 					 generated by UUID.randomUUID().toString()
 ||                 public String name -- hotel's name
 ||                 
 ||
 |+-----------------------------------------------------------------------
 ||
 ||   Constructors:  public Hotel(String name)
 ||
 ||  Inst. Methods:  public String toString() -- returns field vals as a comma-separated string
 ||                  String getFields() -- returns field names matching DB columns
 ||                  
 ++-----------------------------------------------------------------------*/
public class Hotel {

	public String hotelId;
	public String name;

	public Hotel(String name) {
		this.hotelId = UUID.randomUUID().toString();
		this.name = name;
	}

	@Override
	public String toString() {
		return hotelId + ", " + name;
	}

	public String GetFields() {

		StringBuilder sb = new StringBuilder();
		Field[] fields = this.getClass().getDeclaredFields();
		for (Field field : fields) {
			sb.append(field.getName()).append(", ");
		}
		sb.delete(sb.length() - 2, sb.length()); // remove the last ", "
		return sb.toString();
	}

}