/*
 * Rating.java -- Object containing all the data necessary for a single Rating record for Prog4.java
 * 		   		-- This represents the data required for Rating table.
 *             	-- Also contains toString() and GetFields() methods.
 *
 * Author: Mauricio Brooks, Mason Mariani, Arnav Popat
 *
 * First Version: 2023-05-02.
 */

package prog4;

import java.lang.reflect.Field;
import java.util.UUID;

/*+----------------------------------------------------------------------
 ||
 ||  Class Rating 
 ||
 ||         Author:  Mauricio Brooks, Mason Mariani, Arnav Popat
 ||        Purpose:  Object containing all the data necessary for a single 
 ||						Rating in the rating company DB for Prog4.java
 ||                   
 ||
 ||  Inherits From:  None.
 ||
 ||     Interfaces:  None.
 ||
 |+-----------------------------------------------------------------------
 ||      Fields:  
 ||                 public String ratingId -- unique id of rating,
 || 					 generated by UUID.randomUUID().toString()
 ||                 public int rating -- rating for the amenity
 ||                 public String comments -- comments for the amenity rating
 ||                 public String amenityId -- unique id of amenity being rated
 ||                 
 ||
 |+-----------------------------------------------------------------------
 ||
 ||   Constructors:  public Rating(int rating, String comments, String amenityId)
 ||
 ||  Inst. Methods:  public String toString() -- returns field vals as a comma-separated string
 ||                  String getFields() -- returns field names matching DB columns
 ||                  
 ++-----------------------------------------------------------------------*/
public class Rating {

	public String ratingId;
	public int rating;
	public String comments;
	public String amenityId;

	public Rating(int rating, String comments, String amenityId) {
		this.ratingId = UUID.randomUUID().toString();
		this.rating = rating;
		this.comments = comments;
		this.amenityId = amenityId;
	}

	@Override
	public String toString() {
		return ratingId + "," + rating + "," + comments + "," + amenityId;
	}

	public String GetFields() {

		StringBuilder sb = new StringBuilder();
		Field[] fields = this.getClass().getDeclaredFields();
		for (Field field : fields) {
			sb.append(field.getName()).append(", ");
		}
		sb.delete(sb.length() - 2, sb.length()); // remove the last ", "
		return sb.toString();
	}

}
