/*
 * Room.java -- Object containing all the data necessary for a single Room record for Prog4.java
 * 		   		-- This represents the data required for Room table.
 *             	-- Also contains toString() and GetFields() methods.
 *
 * Author: Mauricio Brooks, Mason Mariani, Arnav Popat
 *
 * First Version: 2023-05-02.
 */

package prog4;

import java.lang.reflect.Field;
import java.util.UUID;

/*+----------------------------------------------------------------------
 ||
 ||  Class Room 
 ||
 ||         Author:  Mauricio Brooks, Mason Mariani, Arnav Popat
 ||        Purpose:  Object containing all the data necessary for a single 
 ||						Room in the room company DB for Prog4.java
 ||                   
 ||
 ||  Inherits From:  None.
 ||
 ||     Interfaces:  None.
 ||
 |+-----------------------------------------------------------------------
 ||      Fields:  
 ||                 public String roomId -- unique id of room,
 || 					 generated by UUID.randomUUID().toString()
 ||                 public String hotelId -- unique id of hotel for this room
 ||				 	public float amenitiesTotal -- total cost of amenities for this room
 ||                 public float roomRate -- cost of room per night
 ||                 
 ||                 
 ||
 |+-----------------------------------------------------------------------
 ||
 ||   Constructors:  public Room(String hotelId, float roomRate)
 ||
 ||  Inst. Methods:  public String toString() -- returns field vals as a comma-separated string
 ||                  String getFields() -- returns field names matching DB columns
 ||                  
 ++-----------------------------------------------------------------------*/
public class Room {

	public String roomId;
	public String hotelId;
	public float amenitiesTotal;
	public float roomRate;

	public Room(String hotelId, float roomRate) {
		this.roomId = UUID.randomUUID().toString();
		this.hotelId = hotelId;
		this.amenitiesTotal = 0;
		this.roomRate = roomRate;
	}

	@Override
	public String toString() {
		return roomId + ", " + hotelId + ", " + amenitiesTotal + ", " + roomRate;
	}

	public String GetFields() {

		StringBuilder sb = new StringBuilder();
		Field[] fields = this.getClass().getDeclaredFields();
		for (Field field : fields) {
			sb.append(field.getName()).append(", ");
		}
		sb.delete(sb.length() - 2, sb.length()); // remove the last ", "
		return sb.toString();
	}

}
