package queries;

public class Queries {
	public static final String query1 = // parameter(s): clientId

			
"""
WITH unpaid_amenities AS (
    SELECT 
        hb.clientId,
        ha.amenityId,
        ha.price
    FROM 
        HotelBooking hb
    JOIN 
        HotelAmenity ha ON hb.hotelId = ha.hotelId
    WHERE 
        NOT EXISTS (SELECT 1 FROM HotelRating hr WHERE hr.amenityId = ha.amenityId AND hr.clientId = hb.clientId)
)
SELECT 
    hc.clientId,
    hc.firstName,
    hc.lastName,
    (hr.roomRate * (hb.endDate - hb.startDate) * 
    (1 - 
        (CASE WHEN hc.membershipDiscount = 1 THEN 0.15 ELSE 0 END) - 
        (CASE WHEN hc.creditDiscount = 1 THEN 0.10 ELSE 0 END) - 
        (CASE WHEN hc.isStudent = 1 THEN 0.20 ELSE 0 END)
    )) + COALESCE(SUM(ua.price), 0) AS totalBill
FROM 
    HotelClient hc
JOIN 
    HotelBooking hb ON hc.clientId = hb.clientId
JOIN 
    HotelRoom hr ON hb.hotelId = hr.hotelId AND hb.roomId = hr.roomId
LEFT JOIN 
    unpaid_amenities ua ON ua.clientId = hc.clientId
WHERE 
    hb.clientId = %s
GROUP BY 
    hc.clientId, hc.firstName, hc.lastName, hr.roomRate, hb.startDate, hb.endDate, hc.membershipDiscount, hc.creditDiscount, hc.isStudent;

			
""";
	
	public static final String query2 = // parameter(s): date 
			
"""
SELECT 
    hc.clientId,
    hc.firstName,
    hc.lastName,
    hb.roomId,
    hc.membershipType
FROM 
    HotelClient hc
JOIN 
    HotelBooking hb ON hc.clientId = hb.clientId
WHERE 
    TO_DATE('%s', 'YYYY-MM-DD') BETWEEN hb.startDate AND hb.endDate
ORDER BY 
    hc.membershipType, hb.roomId;

		
""";

	public static final String query3 = // parameters(s): startdate

"""
SELECT 
    he.employeeId,
    he.firstName,
    he.lastName,
    hs.dateStart,
    hs.dateEnd
FROM 
    HotelEmployee he
JOIN 
    HotelShift hs ON he.employeeId = hs.employeeId
WHERE 
    hs.dateStart >=  TO_DATE('%s', 'YYYY-MM-DD') AND hs.dateEnd <= TO_DATE('%s', 'YYYY-MM-DD')
ORDER BY 
    he.employeeId, hs.dateStart;


""";

	
	public static final String query4 = // parameters(s): startdate end date

			
"""
SELECT 
    ha.amenityName,
    AVG(hr.rating) AS averageRating
FROM 
    HotelAmenity ha
JOIN 
    HotelRating hr ON ha.amenityId = hr.amenityId
WHERE 
    hr.ratingDate BETWEEN TO_DATE('%s', 'YYYY-MM-DD') AND TO_DATE('%s', 'YYYY-MM-DD')
GROUP BY 
    ha.amenityName
ORDER BY 
    averageRating DESC;

		
""";
	
	// total revenue generated by a specific hotel between two dates provided by the user. 
	public static final String query5 =
"""
SELECT 
    hh.hotelId,
    hh.name,
    SUM(hr.roomRate * (hb.endDate - hb.startDate) * 
    (1 - 
        (CASE WHEN hc.membershipDiscount = 1 THEN 0.15 ELSE 0 END) - 
        (CASE WHEN hc.creditDiscount = 1 THEN 0.10 ELSE 0 END) - 
        (CASE WHEN hc.isStudent = 1 THEN 0.20 ELSE 0 END)
    )) AS roomRevenue,
    (SELECT SUM(ha.price)
     FROM HotelAmenity ha
     JOIN HotelRating hr ON ha.amenityId = hr.amenityId
     WHERE ha.hotelId = %s AND hr.ratingDate BETWEEN TO_DATE('%s', 'YYYY-MM-DD') AND TO_DATE('%s', 'YYYY-MM-DD')) AS amenityRevenue
FROM 
    HotelHotel hh
JOIN 
    HotelBooking hb ON hh.hotelId = hb.hotelId
JOIN 
    HotelClient hc ON hc.clientId = hb.clientId
JOIN 
    HotelRoom hr ON hb.hotelId = hr.hotelId AND hb.roomId = hr.roomId
WHERE 
    hh.hotelId = %s AND
    hb.startDate >= TO_DATE('%s', 'YYYY-MM-DD') AND hb.endDate <= TO_DATE('%s', 'YYYY-MM-DD')
GROUP BY 
    hh.hotelId,
    hh.name;

""";	
			
}
